### ISSUE TITLE
the weight matrix is different from the original LLGC(zhou et al,2004)?

### ISSUE THREAD

**Issue by herbertchen1** [csyanbin/TPN#2]
I've found that Wii=1 , rather than 0 , will it influence a lot?

**Comment by csyanbin** [comment]
Currently, we haven't experimented with Wii=0.

In LLGC, they set Wii=0 to avoid self-reinforcement.
But in our paper, we think it not necessary to prevent this self-reinforcement.

**Comment by herbertchen1** [comment]
Thanks very much！
