### ISSUE TITLE
pkl.load()

### ISSUE THREAD

**Issue by LYF14020510036** [csyanbin/TPN#4]
Traceback (most recent call last):
  File "test.py", line 122, in <module>
    loader_test.load_data_pkl()
  File "/home/x_y/lyf/TPN/dataset_mini.py", line 86, in load_data_pkl
    data         = pkl.load(f)
_pickle.UnpicklingError: invalid load key, '*'.

hello,could you help me?

**Comment by csyanbin** [comment]
First, please check if the pkl file exists and put in the correct folder.
Second, I use python3. Maybe this problem is caused by python2?

**Comment by LYF14020510036** [comment]
> First, please check if the pkl file exists and put in the correct folder.
> Second, I use python3. Maybe this problem is caused by python2?
thank you very much,I check it again,I find only mini-imagenet-cache-test.pkl has a error.

**Comment by LYF14020510036** [comment]
Thank you very much,I check it again,I find only mini-imagenet-cache-test.pkl has a error.

**Comment by csyanbin** [comment]
I think you'd better check if mini-imagenet-cache-test.pkl is corrupted.
Eg, you can run the following command in python:
```
import pickle as pkl
test = pkl.load(open('mini-imagenet-cache-test.pkl', 'rb'))

**Comment by LYF14020510036** [comment]
Thank you very much,I've tried your advice and find the same error. I'll download a new data.Thanks again.
