### ISSUE TITLE
Question about query sample numbers

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [csyanbin/TPN#5]
Hello, it's really a nice work. And i found when 5*1 test samples, the model has a good performance.  But i wonder if there is only one query sample, does the model has a recognize ability and how to test it?

**Comment by csyanbin** [comment]
Our assumption is that we can make use of the unlabelled query examples to gain better performance.  The one query you mentioned is the so-called inductive in our paper.

We didn't test this setting. If you want to make some experiments, you can simply change the query examples in dataloader or model.py. This should be very simple.
