### ISSUE TITLE
What does ''1600' mean in this line of code, and why is it set to this number?

### ISSUE THREAD

**Issue by clpl** [csyanbin/TPN#6]
Thank you for your nice work. I had a problem while browsing the code.
What does the 1600 dimension in this line of code mean and why is it set to this number?

https://github.com/csyanbin/TPN/blob/3bc9eeaa1d4883ee237c9811cf9eb7c33bfadd24/models.py#L109

**Comment by csyanbin** [comment]
1600 is the feature dimension where feature map is 5x5 and channel number is 64.

**Comment by clpl** [comment]
Thank you.
