### ISSUE TITLE
Code for MAML, Reptile, and Relation Net

### ISSUE THREAD

**Issue by siavash-khodadadeh** [csyanbin/TPN#7]
Hello,

Very interesting paper. Thank you for uploading the code. In the paper the results of applying transductive idea on MAML, Reptile and RelationNet algorithms are reported in table1 and table2. Is there a way to run MAML with transductive in this repository?

**Comment by csyanbin** [comment]
Sorry, we are not releasing this code right now.
Please refer to Section 4.3 in our ICLR paper. We just add a transductive regularized loss on the original classification loss.

**Comment by siavash-khodadadeh** [comment]
I see. Thank you.
